VeloWorldSystem/VeloWorldSystem.Web/Controllers/BikeTypesController.cs
namespace VeloWorldSystem.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using VeloWorldSystem.DtoModels.BikeTypes;
    using VeloWorldSystem.Services.Contracts;
    using VeloWorldSystem.Services.Services;

    public class BikeTypesController : Controller
    {
        private readonly IBikeTypeService bikeTypeService;

        public BikeTypesController(IBikeTypeService bikeTypeServiceParam)
        {
            this.bikeTypeService = bikeTypeServiceParam ?? throw new ArgumentNullException(nameof(BikeTypeService));
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var model = await this.bikeTypeService.GetAllAsync();
            return View(model);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(BikeTypeInputModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await this.bikeTypeService.AddAsync(model);
            return RedirectToAction(nameof(this.All));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await this.bikeTypeService.GetByIdAsync<BikeTypeInputModel>(id);
            if (model == null)
            {
                return this.NotFound();
            }

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, BikeTypeInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.bikeTypeService.UpdateAsync(id, model);
            return RedirectToAction(nameof(this.All));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            return RedirectToAction(nameof(this.All));
        }

        [HttpGet]
        public async Task<IActionResult> Undelete(int id)
        {
            return RedirectToAction(nameof(this.All));
        }
    }
}

VeloWorldSystem/VeloWorldSystem.Web/Controllers/BikesController.cs
namespace VeloWorldSystem.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using VeloWorldSystem.DtoModels.Bikes;
    using VeloWorldSystem.Services.Contracts;

    public class BikesController : AuthorizedController
    {
        private readonly IBikesService bikesService;
        private readonly IBikeTypeService bikeTypeService;

        public BikesController(
            IBikesService bikesService,
            IBikeTypeService bikeTypeService,
            IUsersService usersService)
            : base(usersService)
        {
            this.bikesService = bikesService;
            this.bikeTypeService = bikeTypeService;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var bikeModel = await this.bikesService.GetAllAsync<BikeViewModel>(this.CurrentUserId);
            return View(bikeModel);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var bikeModel = new BikeInputModel() { UserId = this.CurrentUserId, BikeTypes = await this.bikeTypeService.GetAllAsync() };
            return View(bikeModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(BikeInputModel bikeModel)
        {
            if (!await this.bikeTypeService.ExistsAsync(bikeModel.BikeTypeId))
            {
                this.ModelState.AddModelError(nameof(bikeModel.BikeTypeId), "Bike type does not exists.");
            }

            if (bikeModel.UserId != this.CurrentUserId)
            {
                this.ModelState.AddModelError(nameof(bikeModel.UserId), "User does not have a proper permmison for this operation.");
            }

            if (!ModelState.IsValid)
            {
                bikeModel.BikeTypes = await this.bikeTypeService.GetAllAsync();
                return View(bikeModel);
            }

            await this.bikesService.CreateAsync(bikeModel);
            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (!await this.bikesService.ExistsAsync(id))
            {
                return BadRequest();
            }

            if (!await this.bikesService.IsOwner(id, this.CurrentUserId))
            {
                return Unauthorized();
            }

            var bikeModel = await this.bikesService.GetByIdAsync<BikeInputModel>(id);
            bikeModel.BikeTypes = await this.bikeTypeService.GetAllAsync();
            return View(bikeModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, BikeInputModel bikeModel)
        {
            if (!await this.bikesService.ExistsAsync(id))
            {
                return NotFound();
            }

            if (!await this.bikesService.IsOwner(id, this.CurrentUserId))
            {
                return Unauthorized();
            }

            if (!await this.bikeTypeService.ExistsAsync(bikeModel.BikeTypeId))
            {
                this.ModelState.AddModelError(nameof(bikeModel.BikeTypeId), "Bike type does not exists.");
            }

            if (!ModelState.IsValid)
            {
                bikeModel.BikeTypes = await this.bikeTypeService.GetAllAsync();
                return View(bikeModel);
            }

            await this.bikesService.UpdateAsync(id, bikeModel);
            return RedirectToAction(nameof(All));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (!await this.bikesService.ExistsAsync(id))
            {
                return NotFound();
            }

            await this.bikesService.DeleteAsync(id);
            return RedirectToAction(nameof(this.All));
        }
    }
}

VeloWorldSystem/VeloWorldSystem.Web/Views/Shared/_ConfirmDialogs.cshtml
<input id="controllerName" type="hidden" name="controllerName" value="@(ViewContext?.RouteData?.Values["controller"]?.ToString() ?? string.Empty)" />
<input id="areaName" type="hidden" name="areaName" value="@(ViewContext?.RouteData?.Values["area"]?.ToString() ?? string.Empty)" />
<input id="selectedId" type="hidden" name="selectedId" />

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure to delete this record?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" value="Delete" id="confirmDelete">Ok</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="undeleteModal" tabindex="-1" aria-labelledby="undeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="undeleteModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure to undelete this record?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" value="Delete" id="confirmUndelete">Ok</button>
            </div>
        </div>
    </div>
</div>

VeloWorldSystem/VeloWorldSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VeloWorldSystem.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VeloWorldSystem.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @await Html.PartialAsync("_NavigationMenu");
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - VeloWorldSystem.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VeloWorldSystem/VeloWorldSystem.Web/Views/Shared/_NavigationMenu.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VeloWorldSystem.Web</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Bikes" asp-action="All">Bikes</a>
                </li>
                <li class="nav-item" asp-authorize asp-roles="Administrator">
                    <a class="nav-link text-dark" asp-area="Manage" asp-controller="BikeTypes" asp-action="All">Bike Types</a>
                </li>
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>